apiVersion: v1
kind: Service
metadata:
  name: redis-db
  labels:
    app: redis-reader
spec:
  ports:
    - port: 6379
  selector:
    app: redis-reader
    tier: redis-db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-db-pv-claim
  labels:
    app: redis-reader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-db
  labels:
    app: redis-reader
spec:
  selector:
    matchLabels:
      app: redis-reader
      tier: redis-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-reader
        tier: redis-db
    spec:
      containers:
        - image: redis:6.2.7-alpine
          name: redis-db
          ports:
            - containerPort: 6379
              name: redis-db
          volumeMounts:
            - name: redis-db-persistent-storage
              mountPath: /var/lib/redis-db
      volumes:
        - name: redis-db-persistent-storage
          persistentVolumeClaim:
            claimName: redis-db-pv-claim
